[build-system]
requires = ["setuptools>=42", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "dynamixel-sdk"
version = "4.0.3"
description = "Dynamixel SDK 4. python package"
readme = "README.txt"
license = { text = "Apache 2.0" }
authors = [
    { name = "Leon Jung", email = "rwjung@robotis.com" },
    { name = "Wonho Yun", email = "ywh@robotis.com" },
    { name = "Hyungyu Kim", email = "kimhg@robotis.com" }
]
dependencies = [
    "pyserial",
    'importlib_resources; python_version < "3.9"'
]
requires-python = ">=3.6"
urls = { Homepage = "https://github.com/ROBOTIS-GIT/DynamixelSDK" }

[tool.setuptools]
package-dir = {"" = "src"}

[tool.setuptools.packages.find]
where = ["src"]

[tool.setuptools.package-data]
"dynamixel_easy_sdk.control_table" = ["*.model"]
